# Generated by Django 3.0.5 on 2020-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('first_n', models.CharField(max_length=30)),
                ('last_n', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'Signup_teacher',
            },
        ),
    ]
