# Generated by Django 3.0.5 on 2020-07-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence_a', '0002_add_class_add_student_add_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=40, null=True)),
                ('teacher_id', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(null=True)),
                ('present_absent', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Attendence',
            },
        ),
        migrations.CreateModel(
            name='Teacher_subject_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, null=True)),
                ('subject', models.CharField(max_length=20, null=True)),
                ('class_c', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'teacher_subject_class',
            },
        ),
    ]
